### ISSUE TITLE
Category page Display Mode Static Block Only not working good

### ISSUE THREAD

**Issue by jari646** [scandipwa/base-theme#1350] opened 2020-09-30 06:34 UTC
**Description**:
When I adjust Category page Display Mode to Static Block Only, 
I get:
- Category page description
- Info "There were no products found matching your request."
- long white blank space
- and after that CMS block

**Expected behavior**:
It would be nice to get CMS block directly below of Category page description 
and also to get layout update to work 1 column layout

**Versions**:
- ScandiPWA: 3.x-stable
- Magento 2.3.5

**Comment by lianastaskevica** [comment] 2020-10-26 15:16
closing as a duplicate of https://github.com/scandipwa/base-theme/issues/1431

**Closed by lianastaskevica** 2020-10-26 15:16 UTC
Labels: Core, Type: bug, Waiting Estimate
