### ISSUE TITLE
Filtering by position is not working on 2.3.5

### ISSUE THREAD

**Issue by denissdubinin** [scandipwa/base-theme#942] opened 2020-09-04 11:11 UTC
**Description**:
Filtering by position is not working on Magento 2.3.5. In 2.3.x Magento removed code part that adds `catalog_category_product` join which stores product positions. In result products are actually sorted by entity_id.

The issue is fixed in Magento 2.4.

**Expected behavior**:
Products have the same order as it is in admin panel on category edit page.

**To Reproduce**:
1. Go to any category
2. Sort by 'Best match'
3. See that products has incorrect order.

**Versions**:
- ScandiPWA: 3.x
- Magento: 2.3.x

**Comment by denissdubinin** [comment] 2020-09-04 11:13
### Solution
1. `di.xml`
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\ProductSearch">
        <plugin name="vendor_category_product_search_after" type="Vendor\Module\Plugin\BeforeProductSearch" />
    </type>
    <type name="Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\Product\CompositeCollectionProcessor">
        <arguments>
            <argument name="collectionProcessors" xsi:type="array">
                <item name="joinCatalogCategoryProductForPosition" xsi:type="object">
                    Vendor\Module\Model\Resolver\Products\DataProvider\CatalogCategoryProductJoinProcessor
                </item>
            </argument>
        </arguments>
    </type>
</config>
```

2. `Vendor\Module\Model\Resolver\Products\DataProvider\CatalogCategoryProductJoinProcessor`
```
<?PHP

declare(strict_types=1);

namespace Vendor\Module\Model\Resolver\Products\DataProvider;

use Magento\Catalog\Model\ResourceModel\Product\Collection;
use Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\Product\CollectionProcessorInterface;
use Magento\Framework\Api\Filter;
use Magento\Framework\Api\SearchCriteriaInterface;
use Magento\Framework\Exception\LocalizedException;

class CatalogCategoryProductJoinProcessor implements CollectionProcessorInterface
{
    /**
     * @param Collection $collection
     * @param SearchCriteriaInterface $searchCriteria
     * @param array $attributeNames
     * @return Collection
     */
    public function process(
        Collection $collection,
        SearchCriteriaInterface $searchCriteria,
        array $attributeNames
    ): Collection
    {
        if ($categoryFilter = $this->getFilterByFieldName($searchCriteria, 'category_id')) {
            if (is_array($categoryFilter->getValue())) {
                $categoryValue = implode((array)$categoryFilter->getValue(), ',');
            } else {
                $categoryValue = $categoryFilter->getValue();
            }

            try {
                $collection->joinField(
                    'position',
                    'catalog_category_product',
                    'position',
                    'product_id=entity_id',
                    '{{table}}.category_id IN (' . $categoryValue . ')',
                    'inner'
                );
            } catch (LocalizedException $e) {
                // Join already exist
                return $collection;
            }
        }

        return $collection;
    }

    /**
     * @param SearchCriteriaInterface $searchCriteria
     * @param $fieldName
     * @return Filter|mixed|null
     */
    private function getFilterByFieldName(SearchCriteriaInterface $searchCriteria, $fieldName)
    {
        foreach ($searchCriteria->getFilterGroups() as $filterGroup) {
            foreach ($filterGroup->getFilters() as $filter) {
                if ($filter->getField() === $fieldName) {
                    return $filter;
                }
            }
        }

        return null;
    }
}
```

3. `Vendor\Module\Plugin\BeforeProductSearch`
```
<?php

declare(strict_types=1);

namespace Vendor\Module\Plugin;

use Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\ProductSearch;
use Magento\Framework\Api\Search\SearchResultInterface;
use Magento\Framework\Api\SearchCriteriaInterface;

class BeforeProductSearch
{
    /**
     * @param ProductSearch $productSearch
     * @param SearchCriteriaInterface $searchCriteria
     * @param SearchResultInterface $searchResult
     * @param array $attributes
     * @return array
     */
    public function beforeGetList(
        ProductSearch $productSearch,
        SearchCriteriaInterface $searchCriteria,
        SearchResultInterface $searchResult,
        array $attributes = []
    )
    {
        $filterGroup = $searchResult->getSearchCriteria()->getFilterGroups()[0];

        if ($filterGroup->getFilters()[0]->getField() == 'category_id') {
            $searchCriteria->setFilterGroups([$filterGroup]);
        }

        return [$searchCriteria, $searchResult, $attributes];
    }
}
```

**Comment by yeegor** [comment] 2020-09-21 07:34
@lion152 please comment on why did you close this

**Comment by aleksandrakorolova** [comment] 2020-11-17 12:28
Can't reproduce on ScandiPWA 3.2.1
http://scandipwapmrev.indvp.com/default/accessories/accessories-bags?sortKey=position&sortDirection=ASC
![image](https://user-images.githubusercontent.com/73526235/99390236-f863af80-28e0-11eb-8b80-78b9cd8287b9.png)
![image](https://user-images.githubusercontent.com/73526235/99390248-fc8fcd00-28e0-11eb-9372-84afa4769451.png)

**Closed** 2020-11-17 12:30 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
