### ISSUE TITLE
Url Issue

### ISSUE THREAD

**Issue by peterflex7** [scandipwa/base-theme#600] opened 2020-04-17 11:46 UTC
Hello @alfredsgenkins,
    is there is any way of eliminating category & product prams from URL as there is an issue with the URL
if anyone tries to hit a direct URL of category like this?
https://demo.scandipwa.com/category/women (its work) 
https://demo.scandipwa.com/women (doest work) 
sometimes it crashes the application

**Comment by alfredsgenkins** [comment] 2020-04-17 12:24
Already fixed in 2.11.1, demo, sadly is not a latest release. Use url rewrites. The canonical url of /category/woman will lead to correct url /woman

So do not worry about this :)

**Comment by peterflex7** [comment] 2020-04-17 18:56
Your right but @alfredsgenkins I'm facing an issue when someone hits any category URL directly without i.e category in between like domain.com/{woman} i got this page visable 
<img width="379" alt="Screen Shot 2020-04-17 at 4 41 15 PM" src="https://user-images.githubusercontent.com/26825774/79604090-e893ab00-8106-11ea-909c-3b260972fd30.png">
any suggestion whats happenning here ?
in linux centos scandipwa 2.11.1

**Comment by alfredsgenkins** [comment] 2020-04-17 19:31
This looks like a default Magento 2 theme. Very strange you see this. It should never appear while ScandiPWA is enabled. Can you please validate a theme of yours is of type 4?

**Comment by peterflex7** [comment] 2020-04-18 17:46
Hmmm..... I have worked and search on this and found that the issue occurs from the user agent rules I have set ScandiPWA with the user agent rule now i have to find a solution for this

**Comment by peterflex7** [comment] 2020-04-19 11:39
the error i have found in apache logs is this 
magento 2 Uncaught TypeError: Argument 2 passed to Magento\Catalog\Block\Product\ImageFactory::getLabel() must be of the type string
which means some issues from theme's view.xml I have just updated the scandipwa theme's view.xml and add some more line's of code issue resolved now :')

**Comment by peterflex7** [comment] 2020-04-30 11:30
Hi @alfredsgenkins there is one more change required to the code.
(Use Flat Catalog Category field) When this set to Yes you will face an issue with the URL.

domain.com/category/women/women-dresses (Scandipwa URL) This Works fine.

domain.com/women(Native Magento URL)This Works fine.

domain.com/women-dresses (Native Magento URL) This won't work because in this cause 
url_path = women/women-dresses; 
this._getCategoryUrlPath() = women-dresses;

so the below code wouldn't render products.

    getIsNewCategory() {
        const { category: { url_path } = {} } = this.props;
        return url_path !== this._getCategoryUrlPath();
    }

**Solution**

getIsNewCategory should use url_key instead of the URL path for second-level categories.

url_key =  women-dresses;
url_path = women/women-dresses; 
this._getCategoryUrlPath() = women-dresses;

now for the second-level category when Flat Catalog Category set to Yes the application render products fine for native Magento 2 URL.

I have Just set a condition in the above code now all the Magento native URLs works fine now

**Comment by alfredsgenkins** [comment] 2020-04-30 16:13
I do not think that is the issue. Further more the proper flat category support will be released in upcoming version.

I do not know why this breaks the URL loading. I think that is because you are trying to load by url rewrite. If you omit the the "/category" part.

The path loading is intentional, without it the category/women/dress will not work at all.

Additionally, what is you current ScandiPWA version? I remember URL rewrites were fixed in recent releases.

**Comment by alfredsgenkins** [comment] 2020-04-30 16:17
Let me know if I am mistaken, and I will take a look on issue you reported. Again, to reproduce:
0. Try opening sub category by url key
1. Switch Flat categories
2. Try opening subcategory again by url key
3. Notice it is not loading with flat enbled

What is exact path you at testing?

**Comment by peterflex7** [comment] 2020-05-01 19:29
@alfredsgenkins The issue is simple when try to open native Magento 2 URL (Sub-category which I have mentioned above) without /category or with doesn't matter the category page loaded all the graphql request works properly category name visible but products not render because there is a condition
return url_path !== this._getCategoryUrlPath();
which pass this to productlist to render products of that sub caategory
 <CategoryProductList
                  filter={ filter }
                  search={ search }
                  sort={ selectedSort }
                  selectedFilters={ selectedFilters }
                  getIsNewCategory={ getIsNewCategory }
/>

for testing this I just do this 

getIsNewCategory() {
    const { category: { url_key } = {} } = this.props;
    return url_key !== this._getCategoryUrlPath();
}

everything works fine now I have added a condition if url_path fails to match use url_key to render now products also render fine for all type of URL attempts :')

logic is simple you can see the gql request the url_path returns you the URL with parent category & the request URL is without parent category.

when you try to open this https://domain.com/women-dresses
gql return the url_path = women/women-dresses so the products don't render
if you check the URL key it's having the same URL as your request.
  
https://domain.com/women-dresses
(render the category information but products just loading & loading due to the above reason)

url_key = women-dresses;
url_path = women/women-dresses;
this._getCategoryUrlPath() = women-dresses;

**Comment by alfredsgenkins** [comment] 2020-08-25 13:35
With new URL-rewrites in place, this should no-longer be an issue.

**Closed by alfredsgenkins** 2020-08-25 13:35 UTC
