### ISSUE TITLE
Custom mixins from src/app/style/abstract does not work for latest version (3.1.4)

### ISSUE THREAD

**Issue by yostsone** [scandipwa/base-theme#1641] opened 2020-11-09 15:20 UTC
**Description**:
Custom mixins are added inside src/app/style/abstract/ but they can't be found.

**Expected behavior**:
Custom mixins can be added and used inside theme.

**To Reproduce**:
1. Go to src/app/style/abstract/ in custom theme
2. Create new file e.g. _mixins.scss
3. Use your new mixin in theme styles

**Versions**:
- ScandiPWA: 3.1.4

**Additional context**:
After communication with PWA team got following solution for this situation (which I didn't find in the docs)
Change this:
`env.BUILD_MODE === DEVELOPMENT ? fallbackRoot : projectRoot` 
to this:
`projectRoot`

in webpack configs.

**Comment by lianastaskevica** [comment] 2020-11-20 14:10
Hey @yostsone! The issue is fixed in the Create ScandiPWA App - https://scandipwa.gitbook.io/create-scandipwa-app/

**Closed by lianastaskevica** 2020-11-20 14:10 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
