### ISSUE TITLE
Country choice breaks in checkout

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#231] opened 2019-07-23 16:59 UTC
**Describe the bug**
When I change my country in the shipping address during checkout, it allows doing so only for two times. Then it becomes impossible to change the value and the error of `Uncaught TypeError: Cannot read property 'region' of undefined` appears in the console. 

**To Reproduce**
1. Go to checkout
2. Try to change the country several times
3. **Notice the country does not change anymore** 
4. **Notice the error in the console**

**Expected behavior**
No error should appear, I should be able to change the country.

**Comment by mihailspopovs4** [comment] 2019-09-24 09:42
Could not reproduce. Probably fixed in https://github.com/scandipwa/base-theme/pull/252

**Closed** 2019-10-16 12:57 UTC
