### ISSUE TITLE
Attributes order doesn't change if attributes position was changed in the admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1550] opened 2020-10-29 13:42 UTC
**Description**:
Attributes order doesn't change if attributes position was changed in the admin panel
 
**Expected behavior**:
The first attribute X is displayed but the second - attribute Y

**To Reproduce**:
1. Open admin panel -> Store -> Attribute -> Product -> Open attribute X in edit mood -> Enter '1' in the Position field -> Tap 'Save'
2. Open attribute Y in edit mood -> Enter '2' in the Position field -> Tap 'Save'
3. Open website -> Open category page where attributes are displayed

**Actual result:**:
The order doesn't change

**Comment by lianastaskevica** [comment] 2020-11-17 11:56
closing as a duplicate of https://github.com/scandipwa/base-theme/issues/1345

**Closed by lianastaskevica** 2020-11-17 11:56 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
