### ISSUE TITLE
Webpack config style compile. Wrong path.

### ISSUE THREAD

**Issue by maleksandr** [scandipwa/base-theme#1445] opened 2020-10-19 10:53 UTC
**Description**:

webpack.development.config file contains next:

{
                            loader: 'sass-resources-loader',
                            options: {
                                resources: path.join(
                                    env.BUILD_MODE === DEVELOPMENT ? fallbackRoot : projectRoot,
                                    'src', 'app', 'style', 'abstract', '_abstract.scss'
                                )
                            }
                        }

when env.BUILD_MODE === DEVELOPMENT  is True it takes fallbackRoot.
fallbackRoot = path.resolve(magentoRoot, 'vendor', 'scandipwa', 'source');

So it watches to Vendor folder, not Theme folder. That causes an issue - e.g. with custom Mixins.
Same in Production mode.

**Versions**:
- ScandiPWA:  3.1.4

**Comment by lianastaskevica** [comment] 2020-10-26 15:13
closing as a duplicate of https://github.com/scandipwa/base-theme/issues/1425

**Closed by lianastaskevica** 2020-10-26 15:13 UTC
Labels: Core, Type: bug, Waiting Estimate
