### ISSUE TITLE
Fallback for CMS block images is not working

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#139] opened 2019-04-24 14:43 UTC
**Describe the bug**
PWA is not able to display images that are uploaded to wysiwyg and then added to cms block through magento helpers.

**To Reproduce**
upload image to media/wysiwyg and include it in CMS block like this:
```
<img src="{{media url="wysiwyg/cms/footer/logo.png"}}" alt="">
```
on pwa this is parsed as 
```
<picture class="Image Image_ratio_square">
  <source srcset="https://scandipwa.local/media/webp/wysiwyg/cms/footer/logo.webp" type="image/webp">
  <source srcset="https://scandipwa.local/media/wysiwyg/cms/footer/logo.png" type="image/jpeg">
  <source srcset="https://scandipwa.local/media/wysiwyg/cms/footer/logo.png">
  <img src="https://scandipwa.local/media/svg/wysiwyg/cms/footer/logo.svg" alt="">
</picture>
```
the 3rd one is correct, but it defaults to last svg which is 404

In case of svg path is modified to incorrect
```
<picture class="Image Image_ratio_square Image_isLoaded_undefined"><img src="https://scandipwa.local/media/svg/wysiwyg/cms/footer/youtube.svg" alt=""></picture>
```
where path should be `https://scandipwa.local/media/wysiwyg/cms/footer/youtube.svg`

**Expected behavior**
You should be able to see image in CMS block. It should not default to broken URL.

**Comment by eli-l** [comment] 2019-04-24 22:53
Upload and convert functionality was never implemented on the backend. Not a bug. Feel free to adjust image paths to your project needs or PR missing image handling logic.

@alfred
We should convert it to tracked feature request that had low priority so far.

**Comment by kandrejevs** [comment] 2019-04-25 07:22
@eli-l but what about svg images. if you include svg image in your cms block/page it gets replaced by broken URL anyway.

**Comment by eli-l** [comment] 2019-04-25 08:20
@kandrejevs 
SVGs are used as a step for image loading. This mechanism provides great UX when browsing on slower connection, however, all components share the same abstract components right now and BE - FE mapping and processing is missing. The issue won't be addressed in a few nearest weeks by the core team.

**Comment by alfred** [comment] 2019-04-25 14:09
@eli-l Please make sure to tag the correct user in the future.

**Comment by kandrejevs** [comment] 2019-04-26 05:52
@eli-l , I'm talking about use case when you upload svg and use it as a image, for example, icons in CMS block list.
Currently, src path for svg image is replaced with path that should return low res placeholder, so you either have to upload high res svg to placeholders location or you only will have low res placeholder in your website.

**Comment by kandrejevs** [comment] 2019-04-29 09:01
Same bug with slider, adding image from backend results with broken image on frontend.

**Comment by VadzimBelski-ScienceSoft** [comment] 2019-08-16 03:08
Just solved this in Nginx.

Modify scandipwa-base/deploy/shared/conf/nginx/magento.conf
Find block with comment 

> # Fallback to .jpg files for webp files if they are not found.

modify rewrite like this

`rewrite ^/media/webp(.*)\.webp$ /media/$1.jpg last;`

**Comment by eli-l** [comment] 2019-09-20 10:14
Webp is not in use, closing the ticket.

**Closed by eli-l** 2019-09-20 10:14 UTC
Labels: PRIORITY: LOW, STATUS: ON HOLD, enhancement
