### ISSUE TITLE
Add to cart button gets stuck in loading when adding simple product to cart

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#239] opened 2019-07-30 10:30 UTC
**Describe the bug**
When user adds simple product to cart from category page button gets stuck in loading state due error in query.

**To Reproduce**
1. go to category page
2. add simple product to cart

**Expected behavior**
No errors in console

**Screenshots**
```
Wishlist.query.js:39 Uncaught (in promise) TypeError: Cannot read property 'item_id' of undefined
    at Wishlist.getRemoveProductFromWishlistMutation (Wishlist.query.js:39)
    at WishlistDispatcher.removeItemFromWishlist (Wishlist.dispatcher.js:81)
    at removeProductFromWishlist (AddToCart.container.js:24)
    at AddToCart.afterAdded (AddToCart.component.js:58)
    at AddToCart.component.js:109
```

**Comment by xapiksw** [comment] 2019-07-31 11:31
Duplicate of #229

**Comment by malikahmed1996** [comment] 2019-08-08 12:11
@kandrejevs on category page the add to cart component is placed at:
`vendor/scandipwa/source/src/app/component/AddToCart/AddToCart.component.js`
The product is added but the button is stuck because it tries to remove the the specific item from wishlist array at Line:54
```
        // for configurable products productToBeRemovedAfterAdd will be saved in state
        if (removeWishlistItem || (productToBeRemovedAfterAdd === sku && wishlistItems[id])) {
            const product = wishlistItems[id];

            removeProductFromWishlist({ product, noMessages: true });
        }
```

as removeWishlistItem is boolean operator which is in your case is true and wishlistItems[id] doesn't exist you are getting the error
 
```
Wishlist.query.js:39 Uncaught (in promise) TypeError: Cannot read property 'item_id' of undefined
    at Wishlist.getRemoveProductFromWishlistMutation (Wishlist.query.js:39)
    at WishlistDispatcher.removeItemFromWishlist (Wishlist.dispatcher.js:81)
    at removeProductFromWishlist (AddToCart.container.js:24)
    at AddToCart.afterAdded (AddToCart.component.js:58)
    at AddToCart.component.js:109
```
you can just replace the if condition with and operator (&&) instead of or operator (||)

`if (removeWishlistItem && productToBeRemovedAfterAdd === sku && wishlistItems[id])`

<b>so it only executes the only if `removeWishlistItem` is TRUE and `productToBeRemovedAfterAdd === sku` is TRUE and specific item is in `wishlistItems` array</b>

**Comment by mihailspopovs4** [comment] 2019-09-20 09:59
@xapiksw has marked this issue as duplicate of https://github.com/scandipwa/base-theme/issues/229. It was fixed in https://github.com/scandipwa/base-theme/pull/245

**Closed** 2019-09-20 11:33 UTC
