### ISSUE TITLE
Account Overlay does not close on click away

### ISSUE THREAD

**Issue by ioanmeri** [scandipwa/base-theme#933] opened 2020-09-03 07:30 UTC
**Description**:
MyAccount Overlay does not close on click away

**Versions**:
- base-theme v.3 stable

**Additional context**:
If MyAccount Overlay is open and I click on My Cart, MyAccount Overlay closes but it doesn't open again on click.
Also, if MyAccountOverlay is open and navigate to some page, then it doesn't open on click.

**Comment by sebreens** [comment] 2020-09-08 13:32
I am also experiencing problems with overlays not working properly. For me specifically, the myAccount overlay is constantly closing my custom overlay.
I think that the problem lays in the an incorrect implementation of navigation states. Currently, when you click outside of an overlay this action is triggered:
type(pin):"GOTO_PREVIOUS_NAVIGATION_STATE"
navigationType(pin):"TOP_NAVIGATION_TYPE"
If you have went through 2 overlays it doesn't go back to the default navigation state or the intended one for the page, it rather goes back to the first overlay.

To reproduce: 
Open account overlay, then open search overlay and click outside. 

Result:
The navigationState pin in TOP_NAVIGATION_TYPE
name(pin):'search' => 'customer_account'
title(pin):'Sign in'

Expected outcome: 
Expected it would go back to the page's navigation state:
name(pin):'search' => 'posts-details'
title(pin):'Blog'

**Comment by ioanmeri** [comment] 2020-09-09 11:09
The problem seems to be in setting redux state.

When I click on Cart, Redux ```NavigationReducer > TOP_NAVIGATION_TYPE > navigationState > name``` becomes ```cart_overlay```,

 but when i click on MyAccountOverlay, name doesn't change to ```customer_account``` as it should be.

It could fixed by refactoring the ```app/component/Header/Header.container.js``` 

-------------------------

```onMyAccountButtonClick()``` : ```if (name !== CHECKOUT_ACCOUNT) { ... }``` logic to: 
```
        if (name !== CHECKOUT_ACCOUNT) {

            this.setState({ shouldRenderAccountOverlay: true });

            if (isMobile.any()) {
                return;
            }

            showOverlay(CUSTOMER_ACCOUNT_OVERLAY_KEY);

            setNavigationState({
                name: CUSTOMER_ACCOUNT_OVERLAY_KEY,
                title: 'Sign in',
                // onCloseClick: this.closeOverlay
            });
        } 
```

----------------------------

```onMyAccountOutsideClick()```: ```if (name === CUSTOMER_SUB_ACCOUNT) {``` to:

```if (name === CUSTOMER_SUB_ACCOUNT || name === CUSTOMER_ACCOUNT_OVERLAY_KEY) {```

**Comment by lion152** [comment] 2020-09-18 13:52
Could not reproduce on 3.0.2

**Closed** 2020-09-18 13:52 UTC
Labels: Core, Type: bug, Waiting Estimate
