### ISSUE TITLE
Mobile: Never ending loader when creating an account

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1661] opened 2020-11-12 08:14 UTC
**Description**:
Never ending loader when creating an account if the refresh page - ok
 
**Expected behavior**:
Account profile opens

**To Reproduce**:
1. Open website
2. Tap 'Create account'
3. Complete create new account

**Actual result**:
Never ending loader when creating an account if the refresh page - ok

**Additional context**:
Mobile: Andoid and iOS

**Comment by lianastaskevica** [comment] 2020-11-16 16:49
Closing as a duplicate of https://github.com/scandipwa/base-theme/issues/1611

**Closed by lianastaskevica** 2020-11-16 16:49 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
