### ISSUE TITLE
Add to home screen not working on firefox mobile

### ISSUE THREAD

**Issue by drc0** [scandipwa/base-theme#1548] opened 2020-10-29 09:57 UTC
**Description**:
add to home screen does nothing on firefox for mobile

**Expected behavior**:
adding to home screen working like chrome for mobile

**Versions**:
- ScandiPWA: 3.1.5

**Comment by lion152** [comment] 2020-10-30 08:21
Duplicate of https://github.com/scandipwa/base-theme/issues/1385

**Closed by lion152** 2020-10-30 08:21 UTC
Labels: Core, Type: bug
