### ISSUE TITLE
Respect M2 tax display setting to show prices with taxes

### ISSUE THREAD

**Issue by jari646** [scandipwa/base-theme#1364] opened 2020-10-02 06:08 UTC
**Description**:
Could we show product prices with taxes in shopping cart also? 
Even if I set:
Stores-- Configuration -- Sales -- Tax -- Shopping Cart Display Settings --- All values to Including Tax
still show with out tax

**Additional context**:
I think this can be confusing to normal customers (who buy with taxes)

**Comment by lion152** [comment] 2020-10-02 08:07
This is a duplicate of https://github.com/scandipwa/base-theme/issues/675

**Closed** 2020-11-25 12:50 UTC
Labels: Core, Status: Waiting Estimate, Type: Magento Support

**Comment by aleksandrakorolova** [comment] 2020-11-30 16:49
For found issues created related tasks
