### ISSUE TITLE
Theme does not update after npm run build

### ISSUE THREAD

**Issue by ioanmeri** [scandipwa/base-theme#936] opened 2020-09-03 08:18 UTC
**Description**:
Service worker is caching previous builds

**Expected behavior**:
See theme changes after theme build when page refresh

**To Reproduce**:
1. Visit website
2. Make a theme change (Override a component)
3. npm run build
4. Reload Page
5. The theme change does not appear

**Versions**:
base-theme v.3 stable

**Additional context**:
If I do a hard reload or visit from incognito window the change appears. 

One way to force sw registration is to change file size by one byte or use cache versions and invalidate them on build.

**Comment by alfredsgenkins** [comment] 2020-09-04 08:51
Hmm! Great idea. Indeed, injecting random version hash into SW source could help us show the `update` popup. Thanks for your report!

**Comment by lion152** [comment] 2020-09-18 13:49
Duplicate of https://github.com/scandipwa/base-theme/issues/836

**Closed** 2020-09-18 13:49 UTC
Labels: Core, Type: bug, Waiting Estimate
